title: Selenge Ulam-Urnukh
logo: assets/headshot.jfif
#description: Hi my name is Selenge Ulam-Urnukh. Currently, I am studying at UW for Master of Science Information Management with a track of Data Science and PPMC. 
show_download: true
theme: jekyll-theme-minimal
